services:
  prompttrap-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run uvicorn core.main:app --reload --host 0.0.0.0 --port 8000
